/* Automatically generated by './build/bin/build-entry.js' */

import Button from './components/button/package/index.ts';
import ButtonGroup from './components/button-group/package/index.ts';
import Dropdown from './components/dropdown/package/index.ts';
import DropdownMenu from './components/dropdown-menu/package/index.ts';
import DropdownItem from './components/dropdown-item/package/index.ts';
import Tooltip from './components/tooltip/package/index.ts';

const components = [
  Button,
  ButtonGroup,
  Dropdown,
  DropdownMenu,
  DropdownItem,
  Tooltip,
];

const install = function(Vue, opts = {}) {

  components.forEach(component => {
    Vue.component(component.name, component);
  });

  Vue.prototype.$ELEMENT = {
    size: opts.size || '',
    zIndex: opts.zIndex || 2000
  };


};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
}

export default {
  version: '0.0.1',
  install,
  Button,
  ButtonGroup,
  Dropdown,
  DropdownMenu,
  DropdownItem,
  Tooltip
};
